provider:
  name: faas
  gateway: http://localhost:8080  # can be a remote server

functions:
  nslookup:
    lang: dockerfile
    handler: .
    fprocess: xargs nslookup
    image: jockdarock/nslookupfaas:master
